-- Ensure no NULL usernames remain (run manually beforehand if needed):
-- UPDATE "User" SET "username" = concat('user_', "uniqueID") WHERE "username" IS NULL;

ALTER TABLE "User" ALTER COLUMN "username" SET NOT NULL;
-- Add unique index if not auto-generated by Prisma migrate
CREATE UNIQUE INDEX IF NOT EXISTS "User_username_key" ON "User"("username");